name: Portfolio Frontend Pipeline

on:
  push:
    branches:
      - main
    paths:
      - portfolio-frankmascco/**
      - docker/frontend/**
      - .github/workflows/*-frontend.yml
jobs:
  build-image:
    name: Build FE Docker image
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract project version
        id: extract_version
        run: |
          cd portfolio-frankmascco
          echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: portfolio-frankmascco
          file: docker/frontend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-frontend:latest,${{ secrets.DOCKERHUB_USERNAME }}/portfolio-frontend:${{ steps.extract_version.outputs.VERSION }}

  deploy:
    name: Deploy Frontend
    runs-on: self-hosted
    needs: [ build-image ]
    steps:

      - name: Pull & Run Docker container
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
          # Detener y eliminar contenedor anterior si existe
          docker stop portfolio-frontend || true
          docker rm portfolio-frontend || true

          # Descargar la última imagen del frontend
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-frontend:latest

          # Ejecutar el contenedor
          docker run -d --name portfolio-frontend -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-frontend:latest
          EOF
